// import React from 'react';
// import { Page, Text, View, Document, StyleSheet, Font, PDFViewer, Image } from '@react-pdf/renderer';
// import logo from '../../assets/logo.png';

// const studyType = "PROTOCOL OF MRI STUDY OF THE BRAIN";
// const headerNote1 = 'This report was generated by Advanced Medical Imaging System.';
// const footNote1 = 'This conclusion is not a final diagnosis and requires comparison with clinical and laboratory data.';
// const footNote2 = 'In case of typos, contact phone: {hospital phoneNumber goes here}';

// interface ReportTemplateProps {
//   hospitalDetails: {
//     name: string;
//     department: string;
//     address: string;
//     phone: string;
//   };
//   patientDetails: {
//     name: string;
//     birthYear: string;
//     phoneNumber: string;
//   };
//   imageUrls: string[];
//   conclusionText: string;
//   radiologistName: string;
//   headDoctorName: string;
//   createdAt: Date;
// }

// const ReportTemplate = ({
//   hospitalDetails,
//   patientDetails,
//   imageUrls,
//   conclusionText,
//   radiologistName,
//   headDoctorName,
//   createdAt,
// }: ReportTemplateProps) => (
//   <Document>
//     <Page size="A4" style={styles.body}>
//       {/* Logo and Header */}
//       <Image style={styles.header} fixed alt="report image" width={30} height={30} src={logo} />
//       <Text style={styles.text} fixed>{headerNote1}</Text>

//       {/* Hospital Information */}
//       <Text style={styles.subtitle}>{hospitalDetails.name}</Text>
//       <Text style={styles.subtitle}>{hospitalDetails.department}</Text>
//       <Text style={styles.subtitle}>{hospitalDetails.address}. Contact: {hospitalDetails.phone}</Text>

//       {/* Patient Information */}
//       <Text style={styles.subtitle}>Patient Info</Text>
//       <Text style={styles.text}>Full Name: {patientDetails.name}</Text>
//       <Text style={styles.text}>Birth Year: {patientDetails.birthYear}</Text>
//       <Text style={styles.text}>Phone Number: {patientDetails.phoneNumber}</Text>

//       {/* Observation Details */}
//       <Text style={styles.subtitle}>Hospital Info</Text>
//       <Text style={styles.text}>Radiologist Name: {radiologistName}</Text>
//       <Text style={styles.text}>Head Doctor Name: {headDoctorName}</Text>
//       <Text style={styles.text}>Date: {createdAt.toDateString()}</Text>

//       {/* Brain MRI Scans */}
//       <Text style={styles.subtitle}>{studyType}</Text>
//       {imageUrls.map((url, index) => (
//         <Image key={index} src={url} style={styles.image} />
//       ))}

//       {/* Conclusion */}
//       <Text style={styles.subtitle}>Conclusion</Text>
//       <Text style={styles.text}>{conclusionText}</Text>
//       <Text style={styles.text}>{footNote1}</Text>
//       <Text style={styles.text}>{footNote2.replace('{hospital phoneNumber goes here}', hospitalDetails.phone)}</Text>

//       {/* Footer */}
//       <Text style={styles.text}>CoMed Inc.</Text>
//     </Page>
//   </Document>
// );

// Font.register({
//   family: 'Oswald',
//   src: 'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf'
// });

// const styles = StyleSheet.create({
//   body: {
//     paddingTop: 35,
//     paddingBottom: 65,
//     paddingHorizontal: 35,
//   },
//   title: {
//     fontSize: 24,
//     textAlign: 'center',
//     fontFamily: 'Oswald'
//   },
//   author: {
//     fontSize: 12,
//     textAlign: 'center',
//     marginBottom: 40,
//   },
//   subtitle: {
//     fontSize: 18,
//     margin: 12,
//     fontFamily: 'Oswald'
//   },
//   text: {
//     margin: 12,
//     fontSize: 14,
//     textAlign: 'justify',
//     fontFamily: 'Times-Roman'
//   },
//   image: {
//     marginVertical: 15,
//     marginHorizontal: 100,
//   },
//   header: {
//     fontSize: 12,
//     marginBottom: 20,
//   },
//   pageNumber: {
//     position: 'absolute',
//     fontSize: 12,
//     bottom: 30,
//     left: 0,
//     right: 0,
//     textAlign: 'center',
//     color: 'grey',
//   },
// });

// const sampleData = {
//   patientDetails: {
//     name: "John Doe",
//     birthYear: "1975",
//     phoneNumber: "+1234567890"
//   },
//   hospitalDetails: {
//     name: "St. Mary's Hospital",
//     department: "Radiology",
//     address: "123 Health St., Springfield",
//     phone: "+0987654321"
//   },
//   imageUrls: [
//     "https://firebasestorage.googleapis.com/v0/b/chatwithpdf-30e42.appspot.com/o/images%2F1724335515486.jpg?alt=media&token=3b886b80-3815-4146-b548-1d3dd27e4643",
//     "https://firebasestorage.googleapis.com/v0/b/chatwithpdf-30e42.appspot.com/o/images%2F1724335515486.jpg?alt=media&token=3b886b80-3815-4146-b548-1d3dd27e4643"
//   ],
//   conclusionText: "MRI signs of vascular encephalopathy with the presence of multiple ischemic foci and atrophy of the frontotemporal areas on both sides. Left maxillary sinus cyst. Consultation with a neurologist is recommended. Consultation with an otolaryngologist is recommended.",
//   radiologistName: "Dr. Emily Smith",
//   headDoctorName: "Dr. John Watson",
//   createdAt: new Date(),
// };

// const PDFPreview = () => (
//   <PDFViewer width="100%" height="600">
//     <ReportTemplate {...sampleData} />
//   </PDFViewer>
// );

// export default PDFPreview;